name: libmonet
description: Dynamic, user-friendly, design themes.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  matcher: ^0.12.16
  squadron: ^7.1.0

dev_dependencies:
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  material_color_utilities: ^0.11.1
  build_runner:
  squadron_builder: ^7.1.0
  test: ^1.26.3

flutter: